### ISSUE TITLE
How are the nodes being produced?

### ISSUE THREAD

**Issue by dia007** [lrjconan/GRAN#3]
From the little I understood from the paper, at the t-th generation step, the initial node representation of the already generated graph is calculated and it is using those node representations the GNN produces the edges associated with the current block. 

My question is this: How is the new vertices (associated with the current block generated)? The new vertices must be generated before the edges are.

**Comment by lrjconan** [comment]
New block of vertices are always generated first at each step. Think about the process using adjacency matrix may help you. Every step, there are a block of empty rows (nodes) generated. Then GNN figures out which entries of these rows (associated edges) should be generated.

**Comment by dia007** [comment]
Hi, thank you for the clarification. I have one more question, how is the number of nodes (block size) and the stride size determined during the time of generation?
Thank you very much.

**Comment by lrjconan** [comment]
They are hyperparameters. You should stick to the same choice you use during training for good sample quality. You could vary stride to achieve faster generation at the cost of low quality samples. Please refer to our paper for more details on this trade-off.
