### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by dia007** [lrjconan/GRAN#4]
I am running the code in Google Colaboratory (pytorch version: 1.3.1). The error I am getting references to gran_data.py, the line `edges[ii] += cum_size[ii]`.  I am running the code with the gran_DB.yaml. 
A screenshot of the error is provided. I would appreciate your input in this matter. 

![image](https://user-images.githubusercontent.com/8613933/68952701-9699d280-07c0-11ea-996d-659ad7c69ebd.png)

**Comment by lrjconan** [comment]
Hi, I did not run into this issue before. However, `edges[ii]` should be a torch tensor with type long and `cum_size[ii]` should be a numpy array with type int64. Could you please first debug to check whether this is the case?

**Comment by joeybose** [comment]
I managed to bypass this error with the following changes:
1. Replace https://github.com/lrjconan/GRAN/blob/master/dataset/gran_data.py#L262 with
`edges[ii] = edges[ii] + cum_size[ii]` 
2. Add 
`edges = edges.long()` at the beginning of the inference call right after this line here: https://github.com/lrjconan/GRAN/blob/master/model/gran_mixture_bernoulli.py#L216
