### ISSUE TITLE
Possibility of sending the incomplete adjacency matrix of a graph in test

### ISSUE THREAD

**Issue by sbhttchryy** [lrjconan/GRAN#5]
In gran_mixture_bernoulli.py
 `    A_pad = input_dict['adj'] if 'adj' in input_dict else None
`

My question is during testing, is it possible to send the the adjacency matrix of an incomplete graph as A_pad and see if it gets regenerated again? If yes, is there any thing that I should keep in mind?

**Comment by lrjconan** [comment]
Yes, it is doable to generate the graph conditioned on some existing partial adjacency matrix. I think you need to replace the all-zero pre-allocated the full adjacency matrix with your input adjacency matrix and slightly modify the sampling function.
