### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by Kremlesis** [lrjconan/GRAN#9]
How to get the attributes of nodes and edges in the generated graphs. The current output only contains the adjacency matrix of the graphs. Is there any way we can get the nodes and edges attribute matrix also?
Thanks

**Comment by lrjconan** [comment]
> How to get the attributes of nodes and edges in the generated graphs. The current output only contains the adjacency matrix of the graphs. Is there any way we can get the nodes and edges attribute matrix also?
> Thanks

For the attributes, you can add prediction heads that take the node representations output by the GNN as the input.
